### ISSUE TITLE
Відмінність у щоденній кількості нових підтверджених випадків у даних НСЗУ та ЦГЗ

### ISSUE THREAD

**Issue by devrand** [VasiaPiven/covid19_ua#10]
По-перше, дякую за (єдиний здається) набір відкритих даних по COVID-19 в Україні

Питання:  чи відомо вам, чому відрізняються щоденні дані по підтвердженим випадкам, які репортить щоденно ЦГЗ від ваших даних (хоча загальна кількість за весь час співпадає)?  Відмінність доволі суттєва, напр. для 24 травня це 175(у вас), 259(ЦГЗ) і так майже кожного дня. Важливо знати чому така відмінність?

**Comment by VasiaPiven** [comment]
Доброго дня.
Із опису набору:
_Важливо!
Інформація в розрізі днів агрегується безпосередньо по даті реєстрації підозр, даті тестування/одужання/смерті та **не залежить від дати, коли ці дані було оприлюднено**. В разі отримання нових додаткових відомостей або уточнень за попередні періоди, розподіл всіх показників актуалізується автоматично._

А офіційна статистика МОЗ за добу формується наступним чином: Все що відомо на сьогодні відняти Все що відомо на вчора = Нові за добу. В ці нові входять випадки і уточнення , в тому числі за попередні періоди. У цьому полягає відмінність.

**Comment by devrand** [comment]
Дякую - вже трохи зрозуміліше. Але, хочу уточнити:

- **"дата реєстрація підозри"** - це дата, коли про випадок дізнаються у якомусь медичному закладі? чи це дата звіту цього закладу до "центральної бази"?
- **"дата тестування"** - це дата проведення тесту(коли беруть матеріал для аналізу), чи дата отримання результату? Чи може дата звіту, коли про результат повідомили у "центр"?

Що стосується офіційних даних МОЗ, теж хочу уточнити: чи вірно я зрозумів, що у число нових випадків, про яких вони повідомляють щоденно, можуть входити, умовно кажучи, всі результати тестів, які з'явилися за попередню добу (у тому числі, ті що робили будь-коли, але результат щойно отримали)

**Comment by VasiaPiven** [comment]
> Що стосується офіційних даних МОЗ, теж хочу уточнити: чи вірно я зрозумів, що у число нових випадків, про яких вони повідомляють щоденно, можуть входити, умовно кажучи, всі результати тестів, які з'явилися за попередню добу (у тому числі, ті що робили будь-коли, але результат щойно отримали)
>
Саме так, і не лише за попередню добу.

> "дата реєстрація підозри" - це дата, коли про випадок дізнаються у якомусь медичному закладі? 
> Так

 > "дата тестування" - це дата проведення тесту(коли беруть матеріал для аналізу)  
> Так

Тепер якщо підсумувати все вище сказане, то основна відмінність полягає в тому, що ми уточнюємо дані за попередні періоди враховуючи останню наявну інформацію (можна сказати дані динамічні). 
Дані МОЗ статичні та не уточнюються. Всі зміни враховуються лише в наступний звітний день.
А джерело в обох випадках одне, ЦГЗ.

**Comment by devrand** [comment]
Ще раз дякую.

Наскільки я тепер розумію, дані МОЗ по щоденним новим хворим більше  корелюють не з "реальною" динамікою епідемії, а з тим як працюють лабораторії по тестуванню (та вся система збору інформації по COVID-19), тому що у них дата появи випадку - це дата оголошення інформації

Ваші ж дані по новим випадкам більш точно корелюють з динамікою епідемії. Однак залишається проблема, що свіжі дані (напр. за вчорашній день) не враховують якоїсь частини хворих які вже є, але ще не підтверджені тестуванням. Але з часом надходять  результати тестів, відповідно дані уточнюються і поступово враховують всі випадки на кожне число, якщо я правильно все розумію.

**Comment by VasiaPiven** [comment]
Так, все вірно.
