### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [VasiaPiven/covid19_ua#11]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/AQAD5Y
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by VasiaPiven** [comment]
Hi! 
Yes, we update data daily.

**Comment by reeshmabijosh** [comment]
Hello, Vasia Piven

Thanks for your willingness to contribute.
 Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and
you will get the necessary permissions for editing your dataset.
Then please add relevant metadata - description and keywords to your
dataset.

Thanks
Reeshma K
