### ISSUE TITLE
Наявність сирих даних

### ISSUE THREAD

**Issue by Vanuan** [VasiaPiven/covid19_ua#12]
Чи є у розпоряджені МОЗ/ЦГЗ сирі дані, з яких формується статистика?
Наприклад:
ПІБ, Дата народження, Подія, Дата події

Де подія може бути: підозра, не підтвердження підозри, забір зразка, госпіталізація, підтвердження захворювання, одужання, смерть

Чи надається лише статистика? Якщо лише статистика, то який ідентифікатор використовується для її зведення?

**Comment by VasiaPiven** [comment]
Статистику формуємо на основі 'сирих' деперсоналізованих даних ЦГЗ, в розрізі окремих випадків. Кожен випадок відповідає окремій особі. При формуванні статистики використовуються зокрема такі поля як дата реєстрації підозри, дати тестувань, дата госпіталізації, дата виписки, дата одужання або дата смерті, тощо. На основі цих дат будуються всі показники в датасеті.
