### ISSUE TITLE
ще одне питання по даних

### ISSUE THREAD

**Issue by devrand** [VasiaPiven/covid19_ua#13]
Підкажіть будь-ласка, чи можна із вашого набору визначити щоденну кількість людей, для яких були проведені тести (всього)?  Наприклад, чи можна цим показником вважати щоденні new_susp (взагалі, яке визначення цієї змінної?)

**Comment by VasiaPiven** [comment]
new_susp це нові підозри (унікальні люди, у яких встановлена підозра на ковід). 
Визначити щоденну кількість тестів із цих наборів неможливо, оскільки дані про тестування тут відсутні.
А підозри і тести це зовсім різні показники, так як 1 людину можуть тестувати 2-3 і більше разів.
Дані по щоденному тестуванні нещодавно ЦГЗ почав викладати на свій клауд https://cloud.phc.org.ua/index.php/s/gk98W4s3DZFbwEd

**Comment by devrand** [comment]
Дякую, зрозуміло
