### ISSUE TITLE
кількість одужалих

### ISSUE THREAD

**Issue by slawomirmatuszak** [VasiaPiven/covid19_ua#15]
Доброго дня. В мене є запитання про кількість одужалих. Прочитав цікавий пост на фб і згоден, що в Україні дуже багато людей, які хворіють. На вашу думку облік одужалих ведеться правильно? Це важливо, тому що уряд визначає карантинні заходи виходячи з кількісті «активних» хворих. 
https://www.facebook.com/yevgeniy.ikhelzon/posts/10220860471635687

**Comment by VasiaPiven** [comment]
Однозначно інформація про одужання надходить з певним запізненням (назвемо це часовим лагом). Оскільки наші набори даних оновлюються ретроспективно (тобто, інформація за попередні періоди актуалізується на основі всіх наявних даних на дату оновлення),а офіційна оперативна інформація  МОЗ на дату звітування є незмінною, це певною мірою дозволяє оцінити цей лаг.
Для цього  достатньо співставити оперативні дані МОЗ на певну звітну дату (у минулому, наприклад місяць тому, тиждень тому і тд.) із даними, сформованими на цю дату на сьогодні з наших датасетів/дашборду. Для порівняння рекомендую накласти їх у вигляді 2 кривих на графік, щоб зрозуміти тенденцію. 
Аналогічно буде і з кількістю померлих, можливо і з виявленими загалом. Але там не така суттєва затримка, як із одужавшими.

**Comment by VasiaPiven** [comment]
Для прикладу, дані на 01.08.2020 оновлені **08.09.2020.** 
![image](https://user-images.githubusercontent.com/53167805/92523981-01be0500-f22a-11ea-8335-fd899d5b9fdb.png)
Тепер якщо глянути на оперативні дані, про які було прозвітовано 2020-08-02 в каналах МОЗ або РНБО, (тобто фактично за 01.08.2020), то там по одужавших вже більше  5000 різниці. А у % теж чимало.
![image](https://user-images.githubusercontent.com/53167805/92524489-dd165d00-f22a-11ea-957e-99647f737ea6.png)

**Comment by slawomirmatuszak** [comment]
Дякую за відповідь. Зробив порівняння кількісті одужань вашого набору даних (МОЗ  ретроспективні), даних МОЗ, які оприлюднюються кожен день  (МОЗ оперативні)   і прогнозу (при умові, що людина хворує місяць і 2% хворих вмирає). Цікаво, що до середини липня все це співпадало, але потім почалося сильно відрізнятися, тобто кількість офіційних одужалих набагато менше ніж повинна бути згідно прогнозу. Не знаю чому так, мабуть справа в повільному тестуванні.
Діаграма https://rpubs.com/Slawomir_Matuszak/658103

**Comment by VasiaPiven** [comment]
а чому порівнюєте саме нові за добу? а не кумулятивний тотал? На кумулятивному графіку  тенденція буде більш наочна, мабуть

**Comment by slawomirmatuszak** [comment]
Якщо взяти кумулятивний тотал, виходить схожа історія. Ваш набор, оперативна інформація МОЗ та прогноз до середини липня співпадають, але потом все більше відрізняються. Станом на зараз згідно з прогнозом повинно бути на 15 тис. більше людей які одужали, ніж в офіційної статистиці. 
Діаграма https://rpubs.com/Slawomir_Matuszak/658132 
Я не впевнений чому це так. Мабуть питання в повільному повторному тестуванні.

**Comment by slawomirmatuszak** [comment]
Порівняв ситуацію у Польщі. Виявляться,  що прогноз і офіційні дані дуже схожі. Різниця почалася тільки на почату вересня, коли впродовж декількох днів була рекордна кількість одужань. В принципі можете закрити „issue”, так як воно не стосується вашого набору даних. Але явище цікаве.    
https://rpubs.com/Slawomir_Matuszak/658294

**Comment by VasiaPiven** [comment]
Так, закриваю. 
дякую за візуалізації)
