### ISSUE TITLE
Координати лікарень

### ISSUE THREAD

**Issue by hp0404** [VasiaPiven/covid19_ua#16]
Привіт! 

Чи повернуться в `covid19_by_area_type_hosp_dynamics.csv` колонки `legal_entity_lat`, `legal_entity_lng`?

**Comment by VasiaPiven** [comment]
Привіт! 
Файл став займати більше 100мб, через що гітхаб не хоче його приймати. Довелось тимчасово пожертвувати координатами.
Незабаром, планується зміна структури цього набору даних. 
Наразі, як тимчасове рішення, рекомендую взяти останній наявний файл та зробити словник координат (код ЄДРПОУ ,legal_entity_lat, legal_entity_lng).

**Comment by hp0404** [comment]
Зрозуміло, дякую!
