### ISSUE TITLE
Що означає “is_hospitalization_required”? 

### ISSUE THREAD

**Issue by slawomirmatuszak** [VasiaPiven/covid19_ua#17]
Це кількість пацієнтів в госпіталях? Якщо взяти сьогоднішній день , відфільтрувати 
“is_hospitalization_required”=Так
входить 20,101 осіб. Але сьогодні Степанов сказав, що «кількість пацієнтів, які перебувають безпосередньо в лікарнях складає 16 745 або з підтвердженим діагнозом, або підозрою на коронавірусну хворобу».  
Не розумію звідки така різниця.

**Comment by VasiaPiven** [comment]
is_hospitalization_required -  true/false - ознака, що відображає чи потребував пацієнт госпіталізації під час перебігу хвороби (чи був госпіталізований). 
Оскільки дана ознака прив'язується напряму до пацієнта на всьому періоді дат (незалежно від того, коли саме під час перебігу хвороби він був госпіталізований та скільки часу в госпіталізації пацієнт провів), за нею неможливо встановити точну кількість пацієнтів, які перебувають на госпіталізації в поточний момент часу.
