### ISSUE TITLE
Що сталося з covid19_by_settlement_dynamics.csv?

### ISSUE THREAD

**Issue by UnkindPartition** [VasiaPiven/covid19_ua#18]
Добрий день.

Сьогодні з файлу covid19_by_settlement_dynamics.csv зникли всі дані — що сталося?

**Comment by VasiaPiven** [comment]
Доброго дня!
Відбувся збій при оновленні.
Дякую, вже виправлено.

**Comment by UnkindPartition** [comment]
Дякую!
