### ISSUE TITLE
Зменшилась кількість вилікуваних

### ISSUE THREAD

**Issue by MatrosSkin** [VasiaPiven/covid19_ua#3]
Пару днів назад бачив що кількість вилікуваних людей в Черкаській інфекційній лікарні була 18. На сьогодні, після оновлення вигляду таблички, на все місто Черкаси чомусь лише 11 вилікуваних. Чи можете підказати куди поділась решта?

**Comment by VasiaPiven** [comment]
можливо, там уточнили дату виписки із лікарні або дату одужання. Таким чином, ці хворі на момент одужання вже перебували на самоізоляції, тому вони як 'одужали' тепер відображаються на самоізоляції. (випадок, коли дата виписки із лікарні є менша ніж дата одужання). Але це лише припущення, чому так могло відбутись.

**Comment by VasiaPiven** [comment]
![image](https://user-images.githubusercontent.com/53167805/80952105-ccc81e80-8e01-11ea-9bfd-9fdc38639111.png)
якщо ви про дашборд, то у лікарні на сьогодні 18 і є.  На дашборді є 2 способи представлення даних - за реєстрацією та госпіталіацією. Налаштовується це відповідним перемикачем.
 Реєстрація по м.Черкаси це безпосередньо випадки, які ареєстровані в  місті. Госпіталізація по лікарні - це пацієнти в тому числі із інших міст, які госпіталізовані в цю лікарню. Інколи навіть можуть бути випадки госпіталізації в іншу область.

**Comment by MatrosSkin** [comment]
Зрозумів, дякую, вибачте що сам не зміг зорієнтуватися.
