### ISSUE TITLE
відсутня інформація про кількість зроблених тестів

### ISSUE THREAD

**Issue by vityok** [VasiaPiven/covid19_ua#4]
на жаль не вдалось знайти інформацію про кількість зроблених ПЛР тестів (в розрізі днів)

P.S. стосовно решти: дякую за оприлюднення даних у зручному форматі!

**Comment by VasiaPiven** [comment]
Доброго дня!
Наразі ми не аналізуємо таку інформацію. Розпорядник цієї інформації є ЦГЗ/МОЗ, рекомендую звернутись до них.

**Comment by vityok** [comment]
розумію, шкода, але дякую за ту інформацію, яку ви упорядковуєте та поширюєте в зручному для використання форматі (та місці)

**Comment by vityok** [comment]
відповідь отримана, питання закрите
