### ISSUE TITLE
Data.gov.ua?

### ISSUE THREAD

**Issue by Vanuan** [VasiaPiven/covid19_ua#6]
Чи є можливість оприлюднювати також в кабінеті НСЗУ на порталі відкритих даних?

**Comment by VasiaPiven** [comment]
Для того щоб публікувати офіційно дані на data.gov.ua потрібно бути їх розпорядником. 
В даному випадку,НСЗУ не є їх розпорядником.

**Comment by Vanuan** [comment]
А хто є розпорядником?

**Comment by VasiaPiven** [comment]
Розпорядником є ЦГЗ/МОЗ.
