### ISSUE TITLE
Одруківка в назві області

### ISSUE THREAD

**Issue by hp0404** [VasiaPiven/covid19_ua#8]
Помітив проблему з правописом області у [цьому файлі](https://raw.githubusercontent.com/VasiaPiven/covid19_ua/master/covid19_by_area_type_hosp_dynamics.csv). Несуттєво звісно, але може хибно відображатись на дашбордах.

![image](https://user-images.githubusercontent.com/39014459/82377971-1a14d480-9a2d-11ea-9a7a-f1c952140c29.png)

**Comment by vityok** [comment]
Мені вдалося [обійти](https://github.com/vityok/covid19_ua/commit/88d778715487d10da5a62a6517cb370cc3bd0f42) цей недолік комбінацією:
```{r}
    mutate(registration_area=factor(case_when(
               registration_area == "м. Київ" ~ "м. Київ",
               TRUE ~ stringr::str_to_title(registration_area)))) %>%
```

Тобто,  `м. Київ` залишаємо як є, решту до написання з великої літери.

**Comment by hp0404** [comment]
@vityok круто! якщо проблема не вирішиться, також додам спосіб легко виправити одруківку в `pandas`. але мені здається краще виправляти помилки централізовано в оригінальному джерелі.

**Comment by VasiaPiven** [comment]
Дякую!
Буде враховано.
Ми чистимо дані на вході, але інколи буває щось проскакує)
