### ISSUE TITLE
одрук в даті реєстрації випадку в Одеській області

### ISSUE THREAD

**Issue by vityok** [VasiaPiven/covid19_ua#9]
Останній рядок в `covid19_by_area_type_hosp_dynamics.csv` має очевидно невірні дані:

```
2010-05-24,Одеська,Одеська,Самоізоляція,,,,Жіноча,18-39,Ні,Ні,1,0,0,0,0
```

помітив лише коли оновив [графіки](https://vityok.github.io/covid19_ua/regions_dyn.html) в себе на сторінці

**Comment by VasiaPiven** [comment]
виправлено
